LOCAL_PATH := $(call my-dir)
# Thanks to V4A devs

include $(CLEAR_VARS)
LOCAL_MODULE := Viper4Droid
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := v4a.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
include $(BUILD_PREBUILT)
